import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="static flex flex-col items-center justify-between p-4">
            <h1 className="mb-3 text-3xl font-bold">Device Control</h1>
        </header>
        <nav className="flex flex-col items-center justify-between ">
            <ul>
                <li><a href="/roku">Roku</a></li>
            </ul>
        </nav>
        <main className="flex flex-col items-center justify-between p-1">
          {children}
        </main>
        <footer>
              <p>Built by davemcg3</p>
        </footer>
      </body>
    </html>
  )
}
